name: Build v2rayNG APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
      - run: chmod +x ./gradlew
      - run: ./gradlew assembleDebug -Pandroid.injected.signing.store.file=dummy -Pandroid.injected.signing.store.password=dummy -Pandroid.injected.signing.key.alias=dummy -Pandroid.injected.signing.key.password=dummy --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: v2rayNG-apk
          path: app/build/outputs/apk/debug/app-debug.apk
